# Generated by Django 4.0.4 on 2022-05-17 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=60, verbose_name='ФИО')),
                ('department', models.CharField(max_length=60, verbose_name='Департамент')),
            ],
            options={
                'verbose_name': 'Экспериментатор',
                'verbose_name_plural': 'Экспериментаторы',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('code', models.CharField(max_length=10, verbose_name='Код образца')),
            ],
            options={
                'verbose_name': 'Образец',
                'verbose_name_plural': 'Образцы',
            },
        ),
        migrations.AlterModelOptions(
            name='lab',
            options={'verbose_name': 'Лаборатория', 'verbose_name_plural': 'Лаборатории'},
        ),
        migrations.AlterField(
            model_name='lab',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert_id', models.ManyToManyField(to='laboratories.expert')),
                ('lab_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratories.lab')),
                ('sample_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratories.sample')),
            ],
            options={
                'verbose_name': 'Эксперимент',
                'verbose_name_plural': 'Эксперименты',
            },
        ),
    ]
